# Get all jokes
GET http://localhost:6969/jokes

# Add a joke
# POST http://localhost:6969/jokes
#
# {
#   "id" : "abc123",
#   "joke" : "knock knock; who's there? idk."
# }

# Get the latest joke
GET http://localhost:6969/joke
