# Get all jokes
GET http://localhost:8080/jokes

# Add a joke
POST http://localhost:8080/jokes
Content-Type: application/json

{
  "id" : "abc123",
  "joke" : "knock knock; who's there? idk."
}

# Get joke by id
GET http://localhost:8080/jokes/abc123
