# Get all jokes
GET http://localhost:8080/jokes

# Add a joke
POST http://localhost:8080/jokes
Content-Type: application/json

{
  "id" : "lol",
  "joke" : "Your mom 😎"
}

# Get joke by id
GET http://localhost:8080/jokes/TfVvX0wsci
