### Get all albums
GET http://localhost:8080/albums

### Get album by id
GET http://localhost:8080/albums/4

### Insert an album
POST http://localhost:8080/albums
Content-Type: application/json

{
  "id": "4","title": "Ocatvarium","artist": "Dream Theatre","price": 1000.01
}
